package com.berkeley.irms.warnme.models;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Document(collection = "incidents")
/**
 * Represents an incident that can be reported and tracked within the WarnMe application.
 * Incidents are stored in a MongoDB database and have various fields to capture details about the incident.
 */
public class Incident {

    @Id
    private String id;
    private String title;
    private String description;
    private Location location;
    private String timestamp;
    private String status;
    private String type;
    // Constructors
    public Incident() {
    }

    public Incident(String title, String description,  Location location, String timestamp, String status, String type) {
        this.title = title;
        this.description = description;
        this.location = location;
        this.timestamp = timestamp;
        this.status = status;
        this.type = type;
    }

    // Getters and Setters for all fields
    // ID field does not have a setter as it's generated by MongoDB
    
    public String getId() {
        return id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Location getLocation() {
        return location;
    }

    public void setLocation(Location location) {
        this.location = location;
    }

    public String getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }
}
